<?php
define (DEFAULT_PATH, dirname(__DIR__));
define (CONFIG_PATH, DEFAULT_PATH . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR);
define (CLASS_PATH, DEFAULT_PATH . DIRECTORY_SEPARATOR . 'models' . DIRECTORY_SEPARATOR);
define (PROCESSOR_PATH, DEFAULT_PATH . DIRECTORY_SEPARATOR . 'processors' . DIRECTORY_SEPARATOR);